### ISSUE TITLE
Итератор

### ISSUE THREAD

**Issue by pecourses** [Maksym04/js.data-structures_map_set#1]
https://github.com/Maksym04/js.data-structures_map_set/blob/8ca15d9895240582316ff21f396bae11d84a6af3/js/index.js#L21
- методы keys() и  values() возвращают итераторы. Чтобы получить сами элементы, логично прогнать итератор через for..of либо распределить в массив spread-оператором (как раз они двое с итераторами и работают).

**Comment by Maksym04** [comment]
исправил
